name: NeoProtect
main: ru.SocialMoods.NeoProtect
version: "${version}"
api: ["1.0.0"]
description: Анархичные приваты - для каждого.
depend: ["FormConstructor"]
authors:
  - Miroshka/ForgePlugins Studio
  - SocialMoods
commands:
  verify:
    description: "Подтвердить свой Telegram"
  protect:
    description: "Управление регионом"